blank_issues_enabled: true
contact_links:
  - name: Question about how something works
    url: https://github.com/pzanella/remux/issues/new?labels=question
    about: For general questions, open a blank issue with the "question" label.
